# Generated by Django 4.0.6 on 2022-08-16 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('veti_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('texto', models.CharField(blank=True, max_length=300)),
                ('imagen', models.ImageField(blank=True, upload_to='publicaciones')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veti_auth.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('tipo_animal', models.CharField(max_length=30)),
                ('raza', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='mascotas')),
                ('amo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veti_auth.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=60)),
                ('ciudad', models.CharField(max_length=60)),
                ('zona', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, upload_to='locales')),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veti_auth.veterinario')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('especialidad', models.ImageField(upload_to='')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veti_auth.usuario')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas_usuarios.local')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas_usuarios.mascota')),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veti_auth.veterinario')),
            ],
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, upload_to='certificados')),
                ('fecha', models.DateField()),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veti_auth.veterinario')),
            ],
        ),
    ]
