# Generated by Django 4.0.6 on 2022-08-29 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veti_auth', '0001_initial'),
        ('citas_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='mascota',
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas_usuarios.cita')),
                ('cliente', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='veti_auth.usuario')),
                ('mascota', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='citas_usuarios.mascota')),
            ],
        ),
    ]
