# Generated by Django 4.0.6 on 2022-08-24 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veti_auth', '0001_initial'),
        ('citas_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='cliente',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='veti_auth.usuario'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='mascota',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='citas_usuarios.mascota'),
        ),
    ]
